#!/usr/bin/env bash

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/athos-utils.sh"

check_deps "gum" "fzf" "pacman"

show_logo
echo "Removing Arch packages..."
echo
echo "Press Ctrl+Q to return to menu"
echo

fzf_args=(
  --multi
  --preview 'pacman -Sii {1}'
  --preview-label='ctrl-q: quit, tab: multi-select'
  --preview-label-pos='bottom'
  --preview-window 'down:65%:wrap'
  --bind 'ctrl-q:abort'
  --color 'pointer:green,marker:green'
)

pkg_names=$(pacman -Qq | fzf "${fzf_args[@]}")

if [[ -z "$pkg_names" ]]; then
  exit 0
fi

echo "$pkg_names" | tr '\n' ' ' | xargs sudo pacman -Rcs --noconfirm

show_done
